export const TOOLS_DATA = {
  'AI Chatbots': {
    icon: '🤖',
    color: 'from-blue-500 to-cyan-500',
    tools: [
      { name: 'ChatGPT', url: 'https://chat.openai.com', pricing: 'Free/Paid' },
      { name: 'Claude', url: 'https://claude.ai', pricing: 'Free/Paid' },
      { name: 'DeepSeek', url: 'https://deepseek.com', pricing: 'Free' },
      { name: 'Gemini', url: 'https://gemini.google.com', pricing: 'Free/Paid' },
      { name: 'Grok', url: 'https://grok.com', pricing: 'Free' },
      { name: 'Meta AI', url: 'https://meta.ai', pricing: 'Free' },
      { name: 'MS Copilot', url: 'https://copilot.microsoft.com', pricing: 'Free' },
      { name: 'Perplexity', url: 'https://perplexity.ai', pricing: 'Free/Paid' },
      { name: 'Claude Code', url: 'https://claude.ai', pricing: 'Free/Paid' },
      { name: 'OpenAI Operator', url: 'https://openai.com', pricing: 'Paid' },
      { name: 'Le Chat', url: 'https://mistral.ai', pricing: 'Free/Paid' },
      { name: 'YouChat', url: 'https://you.com', pricing: 'Free/Paid' },
      { name: 'Character AI', url: 'https://character.ai', pricing: 'Free/Paid' },
      { name: 'Pi AI', url: 'https://pi.ai', pricing: 'Free' },
    ],
  },
  'AI Presentation': {
    icon: '🎯',
    color: 'from-pink-500 to-rose-500',
    tools: [
      { name: 'Beautiful AI', url: 'https://beautiful.ai', pricing: 'Paid' },
      { name: 'Gamma', url: 'https://gamma.app', pricing: 'Free/Paid' },
      { name: 'Pitch', url: 'https://pitch.com', pricing: 'Free/Paid' },
      { name: 'Plus AI', url: 'https://plusdocs.com', pricing: 'Paid' },
      { name: 'PopAI', url: 'https://popai.pro', pricing: 'Free/Paid' },
      { name: 'Presentation AI', url: 'https://presentation.ai', pricing: 'Free/Paid' },
      { name: 'Slidesgo', url: 'https://slidesgo.com', pricing: 'Free/Paid' },
      { name: 'Tome', url: 'https://tome.app', pricing: 'Free/Paid' },
      { name: 'Canva Design', url: 'https://canva.com', pricing: 'Free/Paid' },
      { name: 'PowerPoint Copilot', url: 'https://microsoft.com', pricing: 'Paid' },
      { name: 'Prezi AI', url: 'https://prezi.com', pricing: 'Free/Paid' },
      { name: 'Decktopus', url: 'https://decktopus.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Coding': {
    icon: '💻',
    color: 'from-green-500 to-emerald-500',
    tools: [
      { name: 'Askcodi', url: 'https://askcodi.com', pricing: 'Free/Paid' },
      { name: 'Codiga', url: 'https://codiga.io', pricing: 'Free/Paid' },
      { name: 'Cursor', url: 'https://cursor.sh', pricing: 'Free/Paid' },
      { name: 'GitHub Copilot', url: 'https://github.com/features/copilot', pricing: 'Paid' },
      { name: 'Qodo', url: 'https://qodo.ai', pricing: 'Free/Paid' },
      { name: 'Replit', url: 'https://replit.com', pricing: 'Free/Paid' },
      { name: 'Tabnine', url: 'https://tabnine.com', pricing: 'Free/Paid' },
      { name: 'Codeium', url: 'https://codeium.com', pricing: 'Free/Paid' },
      { name: 'CodeWhisperer', url: 'https://aws.amazon.com', pricing: 'Free/Paid' },
      { name: 'JetBrains AI', url: 'https://jetbrains.com', pricing: 'Paid' },
      { name: 'Cody', url: 'https://sourcegraph.com/cody', pricing: 'Free/Paid' },
      { name: 'Continue', url: 'https://continue.dev', pricing: 'Free' },
      { name: 'Phind', url: 'https://phind.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Email': {
    icon: '📧',
    color: 'from-orange-500 to-amber-500',
    tools: [
      { name: 'Clippit AI', url: 'https://clippit.ai', pricing: 'Free/Paid' },
      { name: 'Friday', url: 'https://friday.app', pricing: 'Free/Paid' },
      { name: 'Mailmaestro', url: 'https://mailmaestro.ai', pricing: 'Free/Paid' },
      { name: 'Shortwave', url: 'https://shortwave.com', pricing: 'Free/Paid' },
      { name: 'Superhuman', url: 'https://superhuman.com', pricing: 'Paid' },
      { name: 'HubSpot Email', url: 'https://hubspot.com', pricing: 'Free/Paid' },
      { name: 'Flowrite', url: 'https://flowrite.com', pricing: 'Free/Paid' },
      { name: 'Lavender', url: 'https://lavender.ai', pricing: 'Paid' },
    ],
  },
  'AI Image Generation': {
    icon: '🎨',
    color: 'from-purple-500 to-violet-500',
    tools: [
      { name: 'Adobe Firefly', url: 'https://firefly.adobe.com', pricing: 'Free/Paid' },
      { name
