export const TOOLS_DATA = {
  'AI Chatbots': {
    icon: '🤖',
    color: 'from-blue-500 to-cyan-500',
    tools: [
      { name: 'ChatGPT', url: 'https://chat.openai.com', pricing: 'Free/Paid' },
      { name: 'Claude', url: 'https://claude.ai', pricing: 'Free/Paid' },
      { name: 'DeepSeek', url: 'https://deepseek.com', pricing: 'Free' },
      { name: 'Gemini', url: 'https://gemini.google.com', pricing: 'Free/Paid' },
      { name: 'Grok', url: 'https://grok.com', pricing: 'Free' },
      { name: 'Meta AI', url: 'https://meta.ai', pricing: 'Free' },
      { name: 'MS Copilot', url: 'https://copilot.microsoft.com', pricing: 'Free' },
      { name: 'Perplexity', url: 'https://perplexity.ai', pricing: 'Free/Paid' },
      { name: 'Claude Code', url: 'https://claude.ai', pricing: 'Free/Paid' },
      { name: 'OpenAI Operator', url: 'https://openai.com', pricing: 'Paid' },
      { name: 'Le Chat (Mistral)', url: 'https://mistral.ai', pricing: 'Free/Paid' },
      { name: 'YouChat', url: 'https://you.com', pricing: 'Free/Paid' },
      { name: 'Character.AI', url: 'https://character.ai', pricing: 'Free/Paid' },
      { name: 'Pi AI', url: 'https://pi.ai', pricing: 'Free' },
    ],
  },
  'AI Presentation': {
    icon: '🎯',
    color: 'from-pink-500 to-rose-500',
    tools: [
      { name: 'Beautiful.AI', url: 'https://beautiful.ai', pricing: 'Paid' },
      { name: 'Gamma', url: 'https://gamma.app', pricing: 'Free/Paid' },
      { name: 'Pitch', url: 'https://pitch.com', pricing: 'Free/Paid' },
      { name: 'Plus AI', url: 'https://plusdocs.com', pricing: 'Paid' },
      { name: 'PopAI', url: 'https://popai.pro', pricing: 'Free/Paid' },
      { name: 'Presentation.AI', url: 'https://presentation.ai', pricing: 'Free/Paid' },
      { name: 'Slidesgo', url: 'https://slidesgo.com', pricing: 'Free/Paid' },
      { name: 'Tome', url: 'https://tome.app', pricing: 'Free/Paid' },
      { name: 'Canva Magic Design', url: 'https://canva.com', pricing: 'Free/Paid' },
      { name: 'PowerPoint Copilot', url: 'https://microsoft.com', pricing: 'Paid' },
      { name: 'Prezi AI', url: 'https://prezi.com', pricing: 'Free/Paid' },
      { name: 'Decktopus AI', url: 'https://decktopus.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Coding': {
    icon: '💻',
    color: 'from-green-500 to-emerald-500',
    tools: [
      { name: 'Askcodi', url: 'https://askcodi.com', pricing: 'Free/Paid' },
      { name: 'Codiga', url: 'https://codiga.io', pricing: 'Free/Paid' },
      { name: 'Cursor', url: 'https://cursor.sh', pricing: 'Free/Paid' },
      { name: 'GitHub Copilot', url: 'https://github.com/features/copilot', pricing: 'Paid' },
      { name: 'Qodo', url: 'https://qodo.ai', pricing: 'Free/Paid' },
      { name: 'Replit', url: 'https://replit.com', pricing: 'Free/Paid' },
      { name: 'Tabnine', url: 'https://tabnine.com', pricing: 'Free/Paid' },
      { name: 'Windsur (Codeium)', url: 'https://codeium.com', pricing: 'Free/Paid' },
      { name: 'Amazon CodeWhisperer', url: 'https://aws.amazon.com', pricing: 'Free/Paid' },
      { name: 'JetBrains AI Assistant', url: 'https://jetbrains.com', pricing: 'Paid' },
      { name: 'Cody (Sourcegraph)', url: 'https://sourcegraph.com/cody', pricing: 'Free/Paid' },
      { name: 'Continue.dev', url: 'https://continue.dev', pricing: 'Free' },
      { name: 'Phind', url: 'https://phind.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Email': {
    icon: '📧',
    color: 'from-orange-500 to-amber-500',
    tools: [
      { name: 'Clippit.AI', url: 'https://clippit.ai', pricing: 'Free/Paid' },
      { name: 'Friday', url: 'https://friday.app', pricing: 'Free/Paid' },
      { name: 'Mailmaestro', url: 'https://mailmaestro.ai', pricing: 'Free/Paid' },
      { name: 'Shortwave', url: 'https://shortwave.com', pricing: 'Free/Paid' },
      { name: 'Superhuman', url: 'https://superhuman.com', pricing: 'Paid' },
      { name: 'HubSpot AI Email Writer', url: 'https://hubspot.com', pricing: 'Free/Paid' },
      { name: 'Flowrite', url: 'https://flowrite.com', pricing: 'Free/Paid' },
      { name: 'Lavender', url: 'https://lavender.ai', pricing: 'Paid' },
    ],
  },
  'AI Image Generation': {
    icon: '🎨',
    color: 'from-purple-500 to-violet-500',
    tools: [
      { name: 'Adobe Firefly', url: 'https://firefly.adobe.com', pricing: 'Free/Paid' },
      { name: 'DALL-E', url: 'https://openai.com/dall-e', pricing: 'Paid' },
      { name: 'FLUX.1', url: 'https://flux.ai', pricing: 'Free/Paid' },
      { name: 'Ideogram', url: 'https://ideogram.ai', pricing: 'Free/Paid' },
      { name: 'Midjourney', url: 'https://midjourney.com', pricing: 'Paid' },
      { name: 'Recraft', url: 'https://recraft.ai', pricing: 'Free/Paid' },
      { name: 'StableDiffusion', url: 'https://stability.ai', pricing: 'Free/Paid' },
      { name: 'Leonardo AI', url: 'https://leonardo.ai', pricing: 'Free/Paid' },
      { name: 'Canva AI Image Gen', url: 'https://canva.com', pricing: 'Free/Paid' },
      { name: 'Playground AI', url: 'https://playgroundai.com', pricing: 'Free/Paid' },
      { name: 'Ideogram Canvas', url: 'https://ideogram.ai', pricing: 'Free/Paid' },
      { name: 'FLUX Kontext', url: 'https://flux.ai', pricing: 'Free/Paid' },
    ],
  },
  'AI Spreadsheet': {
    icon: '📊',
    color: 'from-teal-500 to-cyan-600',
    tools: [
      { name: 'Bricks', url: 'https://bricks.so', pricing: 'Free/Paid' },
      { name: 'Formula Bot', url: 'https://formulabot.com', pricing: 'Free/Paid' },
      { name: 'Gigasheet', url: 'https://gigasheet.com', pricing: 'Free/Paid' },
      { name: 'Rows AI', url: 'https://rows.com', pricing: 'Free/Paid' },
      { name: 'SheetAI', url: 'https://sheetai.app', pricing: 'Free/Paid' },
      { name: 'Excel Copilot', url: 'https://microsoft.com', pricing: 'Paid' },
      { name: 'Sheets Gemini', url: 'https://google.com/sheets', pricing: 'Free/Paid' },
      { name: 'Airtable AI', url: 'https://airtable.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Meeting Notes': {
    icon: '📝',
    color: 'from-indigo-500 to-blue-500',
    tools: [
      { name: 'Avoma', url: 'https://avoma.com', pricing: 'Free/Paid' },
      { name: 'Equal Time', url: 'https://equaltime.io', pricing: 'Free/Paid' },
      { name: 'Fathom', url: 'https://fathom.video', pricing: 'Free/Paid' },
      { name: 'Fellow.App', url: 'https://fellow.app', pricing: 'Free/Paid' },
      { name: 'Fireflies', url: 'https://fireflies.ai', pricing: 'Free/Paid' },
      { name: 'Krisp', url: 'https://krisp.ai', pricing: 'Free/Paid' },
      { name: 'Otter', url: 'https://otter.ai', pricing: 'Free/Paid' },
      { name: 'Granola', url: 'https://granola.ai', pricing: 'Free/Paid' },
      { name: 'Notion AI Meeting Notes', url: 'https://notion.so', pricing: 'Free/Paid' },
      { name: 'Zoom AI Companion', url: 'https://zoom.us', pricing: 'Paid' },
      { name: 'Teams Copilot', url: 'https://microsoft.com', pricing: 'Paid' },
    ],
  },
  'AI Workflow Automation': {
    icon: '🔧',
    color: 'from-red-500 to-pink-500',
    tools: [
      { name: 'Integrately', url: 'https://integrately.com', pricing: 'Free/Paid' },
      { name: 'Make', url: 'https://make.com', pricing: 'Free/Paid' },
      { name: 'Monday.com', url: 'https://monday.com', pricing: 'Free/Paid' },
      { name: 'N8n', url: 'https://n8n.io', pricing: 'Free/Open Source' },
      { name: 'Wrike', url: 'https://wrike.com', pricing: 'Free/Paid' },
      { name: 'Zapier', url: 'https://zapier.com', pricing: 'Free/Paid' },
      { name: 'Power Automate AI', url: 'https://powerautomate.microsoft.com', pricing: 'Paid' },
      { name: 'Pipedream', url: 'https://pipedream.com', pricing: 'Free/Paid' },
      { name: 'Relay.app', url: 'https://relay.app', pricing: 'Free/Paid' },
      { name: 'Bardeen', url: 'https://bardeen.ai', pricing: 'Free/Paid' },
    ],
  },
  'AI Writing': {
    icon: '✍️',
    color: 'from-yellow-500 to-orange-500',
    tools: [
      { name: 'Copy.AI', url: 'https://copy.ai', pricing: 'Free/Paid' },
      { name: 'Grammarly', url: 'https://grammarly.com', pricing: 'Free/Paid' },
      { name: 'Jasper', url: 'https://jasper.ai', pricing: 'Paid' },
      { name: 'JotBot', url: 'https://jotbot.ai', pricing: 'Free/Paid' },
      { name: 'Quarkle', url: 'https://quarkle.ai', pricing: 'Free/Paid' },
      { name: 'Quillbot', url: 'https://quillbot.com', pricing: 'Free/Paid' },
      { name: 'Rytr', url: 'https://rytr.me', pricing: 'Free/Paid' },
      { name: 'Sudowrite', url: 'https://sudowrite.com', pricing: 'Paid' },
      { name: 'Writesonic', url: 'https://writesonic.com', pricing: 'Free/Paid' },
      { name: 'Notion AI', url: 'https://notion.so', pricing: 'Free/Paid' },
      { name: 'HyperWrite', url: 'https://hyperwrite.com', pricing: 'Free/Paid' },
      { name: 'Anyword', url: 'https://anyword.com', pricing: 'Free/Paid' },
      { name: 'Frase', url: 'https://frase.io', pricing: 'Free/Paid' },
      { name: 'Scalenut', url: 'https://scalenut.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Scheduling': {
    icon: '📅',
    color: 'from-sky-500 to-blue-600',
    tools: [
      { name: 'Calendly', url: 'https://calendly.com', pricing: 'Free/Paid' },
      { name: 'Clockwise', url: 'https://getclockwise.com', pricing: 'Free/Paid' },
      { name: 'Motion', url: 'https://usemotion.com', pricing: 'Paid' },
      { name: 'Reclaim AI', url: 'https://reclaim.ai', pricing: 'Free/Paid' },
      { name: 'Taskade', url: 'https://taskade.com', pricing: 'Free/Paid' },
      { name: 'Trevor AI', url: 'https://trevorai.com', pricing: 'Free/Paid' },
      { name: 'Sunsama', url: 'https://sunsama.com', pricing: 'Paid' },
      { name: 'Akiflow', url: 'https://akiflow.com', pricing: 'Free/Paid' },
      { name: 'BeforeSunset', url: 'https://beforesunset.ai', pricing: 'Free/Paid' },
    ],
  },
  'AI Knowledge Management': {
    icon: '🧠',
    color: 'from-lime-500 to-green-500',
    tools: [
      { name: 'Mem', url: 'https://mem.ai', pricing: 'Free/Paid' },
      { name: 'Notion AI', url: 'https://notion.so', pricing: 'Free/Paid' },
      { name: 'Tettra', url: 'https://tettra.com', pricing: 'Paid' },
      { name: 'Obsidian AI Plugins', url: 'https://obsidian.md', pricing: 'Free/Paid' },
      { name: 'Capacities', url: 'https://capacities.io', pricing: 'Free/Paid' },
      { name: 'Coda AI', url: 'https://coda.io', pricing: 'Free/Paid' },
    ],
  },
  'AI Video Generation': {
    icon: '🎬',
    color: 'from-fuchsia-500 to-purple-600',
    tools: [
      { name: 'Descript', url: 'https://descript.com', pricing: 'Free/Paid' },
      { name: 'Haiper AI', url: 'https://haiper.ai', pricing: 'Free/Paid' },
      { name: 'Invideo AI', url: 'https://invideo.io', pricing: 'Free/Paid' },
      { name: 'Kling', url: 'https://klingai.com', pricing: 'Free/Paid' },
      { name: 'Krea AI', url: 'https://krea.ai', pricing: 'Free/Paid' },
      { name: 'LTX Studio', url: 'https://ltx.studio', pricing: 'Free/Paid' },
      { name: 'Luma AI', url: 'https://lumalabs.ai', pricing: 'Free/Paid' },
      { name: 'Pika AI', url: 'https://pika.art', pricing: 'Free/Paid' },
      { name: 'Runway', url: 'https://runwayml.com', pricing: 'Free/Paid' },
      { name: 'Sora', url: 'https://openai.com/sora', pricing: 'Paid' },
      { name: 'Veo (Google)', url: 'https://google.com/veo', pricing: 'Free/Paid' },
      { name: 'Sora Turbo (OpenAI)', url: 'https://openai.com', pricing: 'Paid' },
      { name: 'Synthesia', url: 'https://synthesia.io', pricing: 'Free/Paid' },
      { name: 'HeyGen', url: 'https://heygen.com', pricing: 'Free/Paid' },
      { name: 'Captions AI', url: 'https://captions.ai', pricing: 'Free/Paid' },
    ],
  },
  'AI Graphic Design': {
    icon: '🎨',
    color: 'from-rose-500 to-pink-600',
    tools: [
      { name: 'AutoDraw', url: 'https://autodraw.com', pricing: 'Free' },
      { name: 'Canva', url: 'https://canva.com', pricing: 'Free/Paid' },
      { name: 'Design.com', url: 'https://design.com', pricing: 'Free/Paid' },
      { name: 'Framer', url: 'https://framer.com', pricing: 'Free/Paid' },
      { name: 'Microsoft Designer', url: 'https://designer.microsoft.com', pricing: 'Free' },
      { name: 'Uizard', url: 'https://uizard.io', pricing: 'Free/Paid' },
      { name: 'Adobe Express AI', url: 'https://express.adobe.com', pricing: 'Free/Paid' },
      { name: 'Kittl', url: 'https://kittl.com', pricing: 'Free/Paid' },
      { name: 'VistaCreate', url: 'https://vistaCreate.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Data Visualization': {
    icon: '📈',
    color: 'from-cyan-500 to-blue-500',
    tools: [
      { name: 'Deckpilot', url: 'https://deckpilot.io', pricing: 'Free/Paid' },
      { name: 'Flourish', url: 'https://flourish.studio', pricing: 'Free/Paid' },
      { name: 'Julius', url: 'https://julius.ai', pricing: 'Free/Paid' },
      { name: 'Visme', url: 'https://visme.co', pricing: 'Free/Paid' },
      { name: 'Zing Data', url: 'https://zingdata.com', pricing: 'Free/Paid' },
      { name: 'Tableau Pulse AI', url: 'https://tableau.com', pricing: 'Paid' },
      { name: 'Power BI Copilot', url: 'https://powerbi.microsoft.com', pricing: 'Paid' },
      { name: 'Locker AI', url: 'https://locker.ai', pricing: 'Free/Paid' },
      { name: 'Narrative BI', url: 'https://narrative.bi', pricing: 'Paid' },
    ],
  },
  'AI Website Builders': {
    icon: '🌐',
    color: 'from-indigo-500 to-purple-500',
    tools: [
      { name: 'Framer AI Sites', url: 'https://framer.com', pricing: 'Free/Paid' },
      { name: 'Webflow AI', url: 'https://webflow.com', pricing: 'Free/Paid' },
      { name: 'Durable', url: 'https://durable.co', pricing: 'Free/Paid' },
      { name: '10Web', url: 'https://10web.io', pricing: 'Free/Paid' },
      { name: 'Wix ADI', url: 'https://wix.com', pricing: 'Free/Paid' },
      { name: 'Hostinger AI Builder', url: 'https://hostinger.com', pricing: 'Paid' },
      { name: 'Dorik AI', url: 'https://dorik.io', pricing: 'Free/Paid' },
    ],
  },
  'AI Research / Search': {
    icon: '🔬',
    color: 'from-emerald-500 to-teal-500',
    tools: [
      { name: 'Perplexity Deep Research', url: 'https://perplexity.ai', pricing: 'Free/Paid' },
      { name: 'OpenAI Deep Research', url: 'https://openai.com', pricing: 'Paid' },
      { name: 'Elicit', url: 'https://elicit.org', pricing: 'Free/Paid' },
      { name: 'Consensus', url: 'https://consensus.app', pricing: 'Free/Paid' },
      { name: 'Scite AI', url: 'https://scite.ai', pricing: 'Free/Paid' },
      { name: 'Connected Papers', url: 'https://connectedpapers.com', pricing: 'Free/Paid' },
    ],
  },
  'AI Voice & Audio': {
    icon: '🎙️',
    color: 'from-orange-500 to-red-500',
    tools: [
      { name: 'ElevenLabs', url: 'https://elevenlabs.io', pricing: 'Free/Paid' },
      { name: 'Murf AI', url: 'https://murf.ai', pricing: 'Free/Paid' },
      { name: 'Suno', url: 'https://suno.com', pricing: 'Free/Paid' },
      { name: 'Udio', url: 'https://udio.com', pricing: 'Free/Paid' },
      { name: 'PlayHT', url: 'https://playht.com', pricing: 'Free/Paid' },
      { name: 'Resemble AI', url: 'https://resemble.ai', pricing: 'Free/Paid' },
    ],
  },
  'AI Agents': {
    icon: '🤖',
    color: 'from-violet-500 to-purple-500',
    tools: [
      { name: 'OpenAI Operator', url: 'https://openai.com/operator', pricing: 'Paid' },
      { name: 'MultiOn', url: 'https://multionai.com', pricing: 'Free/Paid' },
      { name: 'Lindy', url: 'https://lindy.ai', pricing: 'Free/Paid' },
      { name: 'Adept', url: 'https://adept.ai', pricing: 'Free/Paid' },
      { name: 'Crawl4i', url: 'https://crawl4ai.com', pricing: 'Free' },
      { name: 'Phala Network', url: 'https://phala.network', pricing: 'Free/Open Source' },
    ],
  },
  'AI Resume & Job Search': {
    icon: '💼',
    color: 'from-blue-500 to-cyan-500',
    tools: [
      { name: 'Teal', url: 'https://tealhq.com', pricing: 'Free/Paid' },
      { name: 'Kickresume', url: 'https://kickresume.com', pricing: 'Free/Paid' },
      { name: 'Huntr', url: 'https://huntr.co', pricing: 'Free/Paid' },
      { name: 'ResumeAI', url: 'https://resume.ai', pricing: 'Free/Paid' },
      { name: 'Jobscan', url: 'https://jobscan.co', pricing: 'Free/Paid' },
      { name: 'Sonara', url: 'https://sonara.ai', pricing: 'Free/Paid' },
    ],
  },
  'Additional Useful Tools': {
    icon: '⭐',
    color: 'from-yellow-500 to-orange-500',
    tools: [
      { name: 'Phind', url: 'https://phind.com', pricing: 'Free/Paid' },
      { name: 'DeepL Write', url: 'https://deepl.com/write', pricing: 'Free/Paid' },
      { name: 'Claude AI (Anthropi
